# this is a template based  on startbootstrap: "https://blackrockdigital.github.io"

title:              Sagiv Barhoom 
description:        Information systems,databases infrastructure, project management and more ...
author:             Sagiv barhoom
baseurl:            "/"
url:                "https://sagiv-barhoom.me"

# Social Profiles
twitter_username:   BarhoomSagiv
github_username:    sagivba
#facebook_username:  StartBootstrap
linkedin_username:  sagivba 

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-162783460-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           15
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
